### ISSUE TITLE
Not working right now

### ISSUE THREAD

**Issue by icheyne** [xmillsa/ytDownloader#3]
Firefox with Tampermonkey.

![image](https://user-images.githubusercontent.com/389366/56761240-cc2f8d80-6794-11e9-9c7e-256cc4cfeee3.png)

**Comment by xmillsa** [comment]
Thanks, managed to get "Video Only" and "Audio Only" partially working, some videos works fine, others not at all.
Need to figure out what Youtube have changed before it's working properly... shall update again when I have (hopefully) managed to fix it.

**Comment by icheyne** [comment]
Awesome! Thanks for letting me know.

**Comment by Hobadee** [comment]
I was using a similar but different script which stopped working on all YT videos.  I tried yours out and it appears to be broken on all YT videos as well.

Very likely YT changed some backend stuff.  I saw some comments elsewhere about YT API v2 being deprecated.  I didn't look any further into this, but it looks like you are fetching dating from an API.  Does it need to be updated for the new API?

I'll dig around some more and report back if I find anything.

**Comment by Hobadee** [comment]
Digging in a bit:
It appears you aren't using the API, but rather a reverse-engineered method of getting video data.  This method is: `https://www.youtube.com/get_video_info`.  This was never an official API, but appears to have been widely used by various YT downloaders.  (I found some documentation on the reverse-engineering here: https://tyrrrz.me/blog/reverse-engineering-youtube)

Doing a simple `curl` on that URL now returns a 404, so it would appear that Google has either moved, or completely changed that URL.

I shall continue digging.

**Comment by Hobadee** [comment]
This might possibly be related to: https://github.com/Tyrrrz/YoutubeExplode/issues/530

That being said, I tried adding the `CONSENT` cookie via `curl` and I still got a 404.  Also, if this *is* the issue, `fetch` doesn't allow adding cookies, (https://fetch.spec.whatwg.org/#forbidden-header-name) so another workaround would need to be found.

Edit:
More useful info: https://github.com/Tyrrrz/YoutubeExplode/issues/522

**Comment by Hobadee** [comment]
Found part of the fix here: https://github.com/streamlink/streamlink/pull/3732

We need to add `&html5=1` to the `get_video_info` request.  Doing this will give a 200 response instead of a 404.  That being said we are still getting errors.  Perhaps the response changed?

**Comment by Hobadee** [comment]
It appears that the `get_video_info` method has changed significantly.  I created pull request #4 to resolve the issues this created.
